package fm

import (
	"bufio"
	"go/ast"
	"go/format"
	"go/token"
	"os"
)

const codeComment = `// Spies generated by fm. Do not edit.
// Regenerate by running fm instead.
`

// FileWriter formats an ast.File as a standard go file
// and writes it to disk
type FileWriter struct{}

// Write outputs the ast.File to a file on disk specified by filename
func (w *FileWriter) Write(file *ast.File, filename string) error {
	spyFile, err := os.Create(filename)
	if err != nil {
		return err
	}
	buf := bufio.NewWriter(spyFile)
	_, err = buf.Write([]byte(codeComment))
	if err != nil {
		return err
	}

	err = format.Node(buf, token.NewFileSet(), file)
	if err != nil {
		return err
	}

	return buf.Flush()
}
